CREATE TABLE public.picpay_user (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	cnpj varchar(255) NULL,
	cpf varchar(255) NULL,
	createdat timestamp NULL,
	email varchar(255) NULL,
	encryptedpassword varchar(255) NULL,
	"type" varchar(255) NULL,
	updatedat timestamp NULL,
	CONSTRAINT pk_user PRIMARY KEY (id),
	CONSTRAINT uk_user_email UNIQUE (email),
	CONSTRAINT uk_user_cnpj UNIQUE (cnpj),
	CONSTRAINT uk_user_cpf UNIQUE (cpf)
);


CREATE TABLE public.picpay_transaction (
	id uuid NOT NULL,
	"timestamp" timestamp NULL,
	value numeric(19,2) NULL,
	payee_id int8 NULL,
	payer_id int8 NULL,
	CONSTRAINT pk_transaction PRIMARY KEY (id),
	CONSTRAINT fk_picpay_transaction_payer FOREIGN KEY (payer_id) REFERENCES picpay_user(id),
	CONSTRAINT fk_transaction_payee FOREIGN KEY (payee_id) REFERENCES picpay_user(id)
);

CREATE TABLE public.picpay_wallet (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	balance numeric(19,2) NULL,
	owner_id int8 NULL,
	CONSTRAINT pk_wallet PRIMARY KEY (id),
	CONSTRAINT fk_wallet_owner FOREIGN KEY (owner_id) REFERENCES picpay_user(id)
);